services:

  db:
    image: postgres:17.2
    #restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # volumes:
    #   - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_sample